Sorular:
  0 : "Ben giderim o gider arkamdan tın tın eder ?"
  1 : "İstanbulu kim fethetti ?"
  2 : "İzafiyet teorisi hangi bilim insanına aittir ?"
  3 : "Türkiye Cumhuriyetinin ilk Cumhurbaşkanı kimdir ?"
  4 : "Kepenek giyen kişiler hangi meslekle uğraşır ?"
  5 : "a r k"
  6 : "Ilk #sunucuadıforever Yazan Soruyu Bilir"
  7 : "El Üstünde Kaydırmaca"
  8 : "20.5"
  9 : "45.3
Cevaplar:
  0 : "gölge"
  1 : "fatih sultan mehmet"
  2 : "einstein"
  3 : "atatürk"
  4 : "çoban"
  5 : "kar"
  6 : "#craftmcpeforever"
  7 : "sabun"
  8 : "100"
  9 : "135"
